#!/usr/bin/env bash

SIDE_CAR_DEBUG=true \
AWS_PROFILE=AdministratorAccess-225727539677 \
SIDE_CAR_BLOB_STORE_S3_BUCKET_NAME=eigenlayer-blocklake-test \
SIDE_CAR_BLOB_STORE_S3_PREFIX=test \
SIDE_CAR_BLOB_STORE_S3_REGION=us-east-2 \
SIDE_CAR_BLOB_STORE_S3_ACCESS_KEY_ID="AKIATJDTI5HOQSTKOQ4W" \
SIDE_CAR_BLOB_STORE_S3_SECRET_ACCESS_KEY="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" \
SIDE_CAR_ETHEREUM_RPC_BASE_URL="http://54.198.82.217:8545" \
SIDE_CAR_NETWORK="holesky" \
SIDE_CAR_ENVIRONMENT="preprod" \
SIDE_CAR_POSTGRES_HOST="localhost" \
SIDE_CAR_POSTGRES_PORT="5432" \
SIDE_CAR_POSTGRES_USERNAME="sidecar" \
SIDE_CAR_POSTGRES_PASSWORD="sidecar" \
SIDE_CAR_POSTGRES_DBNAME="sidecar" \
SIDE_CAR_ETHERSCAN_API_KEYS="QIPXW3YCXPR5NQ9GXTRQ3TSXB9EKMGDE34" \
SIDE_CAR_RABBITMQ_USERNAME="guest" \
SIDE_CAR_RABBITMQ_PASSWORD="guest" \
SIDE_CAR_RABBITMQ_HOST="localhost:5672" \
go run cmd/migrate/migrate.go
