#!/usr/bin/env bash

SIDECAR_DEBUG=true \
AWS_PROFILE=AdministratorAccess-225727539677 \
SIDECAR_BLOB_STORE_S3_BUCKET_NAME=eigenlayer-blocklake-test \
SIDECAR_BLOB_STORE_S3_PREFIX=test \
SIDECAR_BLOB_STORE_S3_REGION=us-east-2 \
SIDECAR_BLOB_STORE_S3_ACCESS_KEY_ID="AKIATJDTI5HOQSTKOQ4W" \
SIDECAR_BLOB_STORE_S3_SECRET_ACCESS_KEY="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" \
SIDECAR_ETHEREUM_RPC_BASE_URL="http://54.198.82.217:8545" \
SIDECAR_NETWORK="holesky" \
SIDECAR_ENVIRONMENT="preprod" \
SIDECAR_POSTGRES_HOST="localhost" \
SIDECAR_POSTGRES_PORT="5432" \
SIDECAR_POSTGRES_USERNAME="sidecar" \
SIDECAR_POSTGRES_PASSWORD="sidecar" \
SIDECAR_POSTGRES_DBNAME="sidecar" \
SIDECAR_ETHERSCAN_API_KEYS="QIPXW3YCXPR5NQ9GXTRQ3TSXB9EKMGDE34" \
SIDECAR_RABBITMQ_USERNAME="guest" \
SIDECAR_RABBITMQ_PASSWORD="guest" \
SIDECAR_RABBITMQ_HOST="localhost:5672" \
go run cmd/migrate/migrate.go
